---
name: Snowball-Swedish
version: 1.2
author:
  - 'Ask Solem <ASKSH@cpan.org>'
abstract: Porters stemming algorithm for swedish.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0.42
dynamic_config: 0
provides:
  Lingua::Stem::Snowball::Se:
    file: lib/Lingua/Stem/Snowball/Se.pm
    version: 1.2
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
